project_id = "hbrkvwgtqovbfhtpdsoq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.get-unsplash-image]
verify_jwt = false