// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbrkvwgtqovbfhtpdsoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhicmt2d2d0cW92YmZodHBkc29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTE3NDMsImV4cCI6MjA3MjA2Nzc0M30.L5b-_5JSB1UYaYQY0_p8BNLux_eZMbD07d9iOx0xFxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});